FROM confluentinc/cp-kafka-connect:4.0.0

MAINTAINER Firefly team

COPY debezium-connector-mongodb /opt/connectors/debezium-connector-mongodb
COPY kafka-connect-couchbase /opt/connectors/kafka-connect-couchbase

